/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegistriesRouteImport } from './routes/registries'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IngressRouteImport } from './routes/ingress'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsTokensRouteImport } from './routes/settings/tokens'
import { Route as SettingsSessionsRouteImport } from './routes/settings/sessions'
import { Route as SettingsOciCacheRouteImport } from './routes/settings/oci-cache'
import { Route as SettingsHostedRegistryRouteImport } from './routes/settings/hosted-registry'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments/$deploymentId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesRoute = RegistriesRouteImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IngressRoute = IngressRouteImport.update({
  id: '/ingress',
  path: '/ingress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOciCacheRoute = SettingsOciCacheRouteImport.update({
  id: '/settings/oci-cache',
  path: '/settings/oci-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHostedRegistryRoute = SettingsHostedRegistryRouteImport.update({
  id: '/settings/hosted-registry',
  path: '/settings/hosted-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingress': typeof IngressRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/registries': typeof RegistriesRoute
  '/setup': typeof SetupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/settings/hosted-registry': typeof SettingsHostedRegistryRoute
  '/settings/oci-cache': typeof SettingsOciCacheRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/jobs/': typeof JobsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingress': typeof IngressRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/registries': typeof RegistriesRoute
  '/setup': typeof SetupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/settings/hosted-registry': typeof SettingsHostedRegistryRoute
  '/settings/oci-cache': typeof SettingsOciCacheRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/jobs': typeof JobsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingress': typeof IngressRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/registries': typeof RegistriesRoute
  '/setup': typeof SetupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/settings/hosted-registry': typeof SettingsHostedRegistryRoute
  '/settings/oci-cache': typeof SettingsOciCacheRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/users': typeof SettingsUsersRoute
  '/jobs/': typeof JobsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingress'
    | '/login'
    | '/observability'
    | '/registries'
    | '/setup'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/projects/$projectId'
    | '/services/$serviceId'
    | '/settings/hosted-registry'
    | '/settings/oci-cache'
    | '/settings/sessions'
    | '/settings/tokens'
    | '/settings/users'
    | '/jobs/'
    | '/projects/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingress'
    | '/login'
    | '/observability'
    | '/registries'
    | '/setup'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/projects/$projectId'
    | '/services/$serviceId'
    | '/settings/hosted-registry'
    | '/settings/oci-cache'
    | '/settings/sessions'
    | '/settings/tokens'
    | '/settings/users'
    | '/jobs'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/ingress'
    | '/login'
    | '/observability'
    | '/registries'
    | '/setup'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/projects/$projectId'
    | '/services/$serviceId'
    | '/settings/hosted-registry'
    | '/settings/oci-cache'
    | '/settings/sessions'
    | '/settings/tokens'
    | '/settings/users'
    | '/jobs/'
    | '/projects/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngressRoute: typeof IngressRoute
  LoginRoute: typeof LoginRoute
  ObservabilityRoute: typeof ObservabilityRoute
  RegistriesRoute: typeof RegistriesRoute
  SetupRoute: typeof SetupRoute
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  SettingsHostedRegistryRoute: typeof SettingsHostedRegistryRoute
  SettingsOciCacheRoute: typeof SettingsOciCacheRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsTokensRoute: typeof SettingsTokensRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries': {
      id: '/registries'
      path: '/registries'
      fullPath: '/registries'
      preLoaderRoute: typeof RegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingress': {
      id: '/ingress'
      path: '/ingress'
      fullPath: '/ingress'
      preLoaderRoute: typeof IngressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/oci-cache': {
      id: '/settings/oci-cache'
      path: '/settings/oci-cache'
      fullPath: '/settings/oci-cache'
      preLoaderRoute: typeof SettingsOciCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hosted-registry': {
      id: '/settings/hosted-registry'
      path: '/settings/hosted-registry'
      fullPath: '/settings/hosted-registry'
      preLoaderRoute: typeof SettingsHostedRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngressRoute: IngressRoute,
  LoginRoute: LoginRoute,
  ObservabilityRoute: ObservabilityRoute,
  RegistriesRoute: RegistriesRoute,
  SetupRoute: SetupRoute,
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  SettingsHostedRegistryRoute: SettingsHostedRegistryRoute,
  SettingsOciCacheRoute: SettingsOciCacheRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsTokensRoute: SettingsTokensRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  JobsIndexRoute: JobsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
